### ISSUE TITLE
Create a Dockerfile

### ISSUE THREAD

**Issue by 2moveit** [octopress/docs#49]
It would be great to find a dockerfile here including documentation to setup octopress.

**Comment by parkr** [comment]
This is way beyond the scope of Octopress – *how* you run `octopress` is separate from this.

As a side note, I think @troyswanson has worked on this a bit.

**Comment by 2moveit** [comment]
Ok, I just thought it might be a good idea. It's just one file that helps to start faster with octopress. You know the specs best which ruby version etc. Especially under windows I had some troubles. And I found a couple of dockerfiles but no officially supported with a good documentation that worked smoothly. Felt like a praline, you never know what you get :) But you are right. It's maybe not the best idea to have it directly in octopress. Maybe some recommendations for "each" environment in the documentation is a better idea or another alternative that you may have in mind. Octopress is really great but the setup of the environment at least under windows is't.

**Comment by troyswanson** [comment]
Hey @2moveit - I've done a little work on a barebones Jekyll Docker image.

Feel free to [check it out](https://registry.hub.docker.com/u/troyswanson/jekyll/) and let me know what you think.
